#pragma once

//###################################################################################################################
//самое тупое, что приходилось здесь делать - чтобы визуально вставлять позы lipsynq в зависимости от произносимого звука
//###################################################################################################################
UENUM(BlueprintType) enum class EPhoneme : uint8
{
	S0  UMETA(Hidden),
	S1  UMETA(Hidden),
	S2  UMETA(Hidden),
	S3  UMETA(Hidden),
	S4  UMETA(Hidden),
	S5  UMETA(Hidden),
	S6  UMETA(Hidden),
	S7  UMETA(Hidden),
	S8  UMETA(Hidden),
	S9  UMETA(Hidden),
	S10  UMETA(Hidden),
	S11  UMETA(Hidden),
	S12  UMETA(Hidden),
	S13  UMETA(Hidden),
	S14  UMETA(Hidden),
	S15  UMETA(Hidden),
	S16  UMETA(Hidden),
	S17  UMETA(Hidden),
	S18  UMETA(Hidden),
	S19  UMETA(Hidden),
	S20  UMETA(Hidden),
	S21  UMETA(Hidden),
	S22  UMETA(Hidden),
	S23  UMETA(Hidden),
	S24  UMETA(Hidden),
	S25  UMETA(Hidden),
	S26  UMETA(Hidden),
	S27  UMETA(Hidden),
	S28  UMETA(Hidden),
	S29  UMETA(Hidden),
	S30  UMETA(Hidden),
	S31  UMETA(Hidden),

	AUX_SPACE  UMETA(DisplayName = " "),
	AUX_EXCLM  UMETA(DisplayName = "!"),
	AUX_QUOTE  UMETA(DisplayName = "''"),
	AUX_NUMBR  UMETA(DisplayName = "#"),
	AUX_DOLLR  UMETA(DisplayName = "$"),
	AUX_PRCNT  UMETA(DisplayName = "%"),
	AUX_ETLIG  UMETA(DisplayName = "&"),
	AUX_APOST  UMETA(DisplayName = "'"),
	AUX_BROPN  UMETA(DisplayName = "("),
	AUX_BRCLS  UMETA(DisplayName = ")"),
	AUX_ASTER  UMETA(DisplayName = "*"),
	AUX_PLUS   UMETA(DisplayName = "+"),
	AUX_COMMA   UMETA(DisplayName = ","),
	AUX_MINUS   UMETA(DisplayName = "-"),
	AUX_POINT   UMETA(DisplayName = "."),
	AUX_SLASH   UMETA(DisplayName = "/"),

	NMR_0   UMETA(DisplayName = "0"),
	NMR_1   UMETA(DisplayName = "1"),
	NMR_2   UMETA(DisplayName = "2"),
	NMR_3   UMETA(DisplayName = "3"),
	NMR_4   UMETA(DisplayName = "4"),
	NMR_5   UMETA(DisplayName = "5"),
	NMR_6   UMETA(DisplayName = "6"),
	NMR_7   UMETA(DisplayName = "7"),
	NMR_8   UMETA(DisplayName = "8"),
	NMR_9   UMETA(DisplayName = "9"),

	AUX_COLON   UMETA(DisplayName = ":"),
	AUX_SEMIC   UMETA(DisplayName = ";"),
	AUX_LESS    UMETA(DisplayName = "<"),
	AUX_EQUAL    UMETA(DisplayName = "="),
	AUX_GREAT    UMETA(DisplayName = ">"),
	AUX_QUEST    UMETA(DisplayName = "?"),
	AUX_GRAVE    UMETA(DisplayName = "`"),

	UP_A    UMETA(DisplayName = "A"),
	UP_B    UMETA(DisplayName = "B"),
	UP_C    UMETA(DisplayName = "C"),
	UP_D    UMETA(DisplayName = "D"),
	UP_E    UMETA(DisplayName = "E"),
	UP_F    UMETA(DisplayName = "F"),
	UP_G    UMETA(DisplayName = "G"),
	UP_H    UMETA(DisplayName = "H"),
	UP_I    UMETA(DisplayName = "I"),
	UP_J    UMETA(DisplayName = "J"),
	UP_K    UMETA(DisplayName = "K"),
	UP_L    UMETA(DisplayName = "L"),
	UP_M    UMETA(DisplayName = "M"),
	UP_N    UMETA(DisplayName = "N"),
	UP_O    UMETA(DisplayName = "O"),
	UP_P    UMETA(DisplayName = "P"),
	UP_Q    UMETA(DisplayName = "Q"),
	UP_R    UMETA(DisplayName = "R"),
	UP_S    UMETA(DisplayName = "S"),
	UP_T    UMETA(DisplayName = "T"),
	UP_U    UMETA(DisplayName = "U"),
	UP_V    UMETA(DisplayName = "V"),
	UP_W    UMETA(DisplayName = "W"),
	UP_X    UMETA(DisplayName = "X"),
	UP_Y    UMETA(DisplayName = "Y"),
	UP_Z    UMETA(DisplayName = "Z"),

	AUX_SQOPN    UMETA(DisplayName = "["),
	AUX_TILDE    UMETA(DisplayName = "~"),
	AUX_SQCLS    UMETA(DisplayName = "]"),
	AUX_CARET    UMETA(DisplayName = "^"),
	AUX_UNDER    UMETA(DisplayName = "_"),
	AUX_ATCOM    UMETA(DisplayName = "@"),

	LO_A    UMETA(DisplayName = "-a"),
	LO_B    UMETA(DisplayName = "-b"),
	LO_C    UMETA(DisplayName = "-c"),
	LO_D    UMETA(DisplayName = "-d"),
	LO_E    UMETA(DisplayName = "-e"),
	LO_F    UMETA(DisplayName = "-f"),
	LO_G    UMETA(DisplayName = "-g"),
	LO_H    UMETA(DisplayName = "-h"),
	LO_I    UMETA(DisplayName = "-i"),
	LO_J    UMETA(DisplayName = "-j"),
	LO_K    UMETA(DisplayName = "-k"),
	LO_L    UMETA(DisplayName = "-l"),
	LO_M    UMETA(DisplayName = "-m"),
	LO_N    UMETA(DisplayName = "-n"),
	LO_O    UMETA(DisplayName = "-o"),
	LO_P    UMETA(DisplayName = "-p"),
	LO_Q    UMETA(DisplayName = "-q"),
	LO_R    UMETA(DisplayName = "-r"),
	LO_S    UMETA(DisplayName = "-s"),
	LO_T    UMETA(DisplayName = "-t"),
	LO_U    UMETA(DisplayName = "-u"),
	LO_V    UMETA(DisplayName = "-v"),
	LO_W    UMETA(DisplayName = "-w"),
	LO_X    UMETA(DisplayName = "-x"),
	LO_Y    UMETA(DisplayName = "-y"),
	LO_Z    UMETA(DisplayName = "-z"),

};
